name = "PeptideSeq"
uuid = "bf2bc7d4-d808-419e-874f-43e03236f5cf"
authors = ["yufongpeng <54415349+yufongpeng@users.noreply.github.com> and contributors"]
version = "0.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
CSV = "0.10"
IterTools = "1"
PrettyTables = "1, 2"
julia = "1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
